In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([ 1.41828357,  1.22245606, -0.63071564,  0.50688958, -0.25444067,
        0.09598415, -0.88356864,  0.67175741, -0.98647398, -0.8635009 ])

In [8]:
B = np.random.randn(10)
B

array([ 0.98190577,  0.27649715, -0.32659589,  0.36973026,  0.042598  ,
        0.40618495,  0.40223664, -0.88280521, -0.35395262, -0.02680283])

In [9]:
# Binary functions
np.add(A,B)

array([ 2.40018933,  1.49895321, -0.95731154,  0.87661984, -0.21184267,
        0.5021691 , -0.481332  , -0.2110478 , -1.3404266 , -0.89030374])

In [10]:
np.maximum(A,B)

array([ 1.41828357,  1.22245606, -0.32659589,  0.50688958,  0.042598  ,
        0.40618495,  0.40223664,  0.67175741, -0.35395262, -0.02680283])

In [15]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'

In [16]:
import webbrowser
#webbrowser.open(website)