In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

In [6]:
my_lists = [my_list1,my_list2]

In [7]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [8]:
my_array2 = np.array(my_lists)

In [9]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [10]:
my_array2.shape

(2, 4)

In [11]:
my_array2.dtype

dtype('int64')

In [16]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [18]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [19]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(1,5.5,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])