In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [8]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

print ser1
print ser2

T    0
U    1
V    2
dtype: int64
X    3
Y    4
dtype: int64


In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [14]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [15]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe1

X         Y         Z
0 -1.587926 -0.417089 -1.409232
1  1.204355  0.539194 -0.776915
2 -0.583445  1.796865 -0.215697
3  0.687531  0.411380 -0.097328

In [16]:
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])
dframe2

Y         Q         X
0  2.182923  0.169471  0.833615
1 -2.007758  0.344451  0.531151
2 -1.239030 -0.497277 -0.850928

In [17]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -1.587926 -0.417089 -1.409232
1       NaN  1.204355  0.539194 -0.776915
2       NaN -0.583445  1.796865 -0.215697
3       NaN  0.687531  0.411380 -0.097328
0  0.169471  0.833615  2.182923       NaN
1  0.344451  0.531151 -2.007758       NaN
2 -0.497277 -0.850928 -1.239030       NaN

In [18]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -1.587926 -0.417089 -1.409232
1       NaN  1.204355  0.539194 -0.776915
2       NaN -0.583445  1.796865 -0.215697
3       NaN  0.687531  0.411380 -0.097328
4  0.169471  0.833615  2.182923       NaN
5  0.344451  0.531151 -2.007758       NaN
6 -0.497277 -0.850928 -1.239030       NaN